//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBankManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int DonorId { get; set; }
        public string Name { get; set; }
        public string BloodGroup { get; set; }
        public string RH { get; set; }
        public string MailAdress { get; set; }
        public string PhoneNumber { get; set; }

     
    }
}
